### ISSUE TITLE
Fix for bazar.bg

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#11]
При bazar.bg се блокира само един от поддомейните на focus.bg. Самата реклама е скрита, но картинките се свалят. За да се оправи може филтърът ||cdn4.focus.bg/fakti/*$domain=bazar.bg може да се замени с ||focus.bg*$domain=bazar.bg . При търсене в сайта отдолу остава празно място, което може да се премахне с тези два филтъра:
bazar.bg##.clearfix.search_cont_thumb > div:nth-of-type(4)
bazar.bg##.clearfix.search_cont_thumb > div:nth-of-type(3)

**Comment by Dani-1-2** [comment]
Бележка: поради някаква причина това блокира и снимките на обявите.

**Comment by Dani-1-2** [comment]
Бележка: снимките се съхраняват на focus.bg. Не добавяйте филтъра ||focus.bg*$domain=bazar.bg .

**Comment by RealEnder** [comment]
Супер, благодаря!
