### ISSUE TITLE
blitz.bg

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#2]
Ad in the form of a link at https://blitz.bg/obshtestvo/kak-chk-noris-prebroi-do-bezkraynost-dva-pti-i-kakvo-oshche-ne-znaem-za-nego_news925241.html .
Proposed filters:
blitz.bg##a[href^="https://cdn1.efbet.com"]
And this to remove the empty space left:
blitz.bg##p:nth-of-type(7)

**Comment by RealEnder** [comment]
Thanks!
Fixed in [19ebd63](https://github.com/RealEnder/adblockbg/commit/19ebd631deb8d4e110868a632bcad0dbc275a98c)
