### ISSUE TITLE
bazar.bg

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#3]
Ad for news site appears on the bottom of the page at https://bazar.bg/obiavi?q=nintendo%20switch&sort=weight .

Was able to hide the ads with these filters:

bazar.bg##.last.newsLink.listItemLink
bazar.bg##.listItemLink.newsLink

Can remove the empty space after hiding the ads with these filters:

bazar.bg##div:nth-of-type(70)
bazar.bg##div:nth-of-type(71)

This is the filter to block images from the ad server:
||cdn4.focus.bg/fakti/*$domain=bazar.bg

**Comment by RealEnder** [comment]
Thanks!
Fixed in [19ebd63](https://github.com/RealEnder/adblockbg/commit/19ebd631deb8d4e110868a632bcad0dbc275a98c)
