### ISSUE TITLE
gabarko.eu

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#4]
Ad banners appear on https://www.gabarko.eu/sarnela-macrolepiota-procera/ .
Suggested filters:
||www.gabarko.eu/wp-content/uploads/2022/03/po-profesia-drevar-4*.jpg$image
www.gabarko.eu##.gabar-widget.widget.clean-gallery-box.clean-gallery-side-widget
||www.gabarko.eu/wp-content/uploads/2023/12/$image

**Comment by Dani-1-2** [comment]
Note: filters may not work if the website contents are cached, but work after disabling the cache.

**Comment by RealEnder** [comment]
Thanks!
Fixed in [19ebd63](https://github.com/RealEnder/adblockbg/commit/19ebd631deb8d4e110868a632bcad0dbc275a98c)
