### ISSUE TITLE
pik.bg

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#5]
Ads and ad leftovers at https://pik.bg/%D0%B8%D0%B7%D0%B2%D1%8A%D0%BD%D1%80%D0%B5%D0%B4%D0%BD%D0%BE-%D0%B2-%D1%81%D0%B0%D1%89-%D1%81%D0%B8%D1%82%D1%83%D0%B0%D1%86%D0%B8%D1%8F%D1%82%D0%B0-%D1%81%D1%82%D0%B0%D0%B2%D0%B0-%D0%B2%D0%B7%D1%80%D0%B8%D0%B2%D0%BE%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%B0---%D0%BF%D1%80%D0%B5%D0%BA%D0%B0%D1%80%D0%B2%D0%B0%D1%82-%D1%82%D0%B0%D0%BD%D0%BA%D0%BE%D0%B2%D0%B5-%D0%B8-%D0%B1%D1%80%D0%BE%D0%BD%D0%B8%D1%80%D0%B0%D0%BD%D0%B8-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B8-%D0%BA%D1%8A%D0%BC--news1213783.html and others.
Suggested filters:
pik.bg##[href^="https://record.winbetaffiliates.com/"]
pik.bg##div.left.connected-news-wrap:nth-of-type(2) > .left.connected-news
pik.bg###indexTopRightBox > div.center.w100.left.banners_300x250

**Comment by RealEnder** [comment]
Thanks, fixed in 8d09218ff4c3df9fda9aaba25683744c16dfcc76
