### ISSUE TITLE
gabarko.eu : incorrect blocking

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#6]
The ads are properly blocked on https://www.gabarko.eu/sarnela-macrolepiota-procera/ , but some images are missing on https://www.gabarko.eu/ and many other pages. If I use ||www.gabarko.eu/wp-content/uploads/2023/12/1015643*.jpg$image , the image is not blocked. It is blocked with  ||www.gabarko.eu/wp-content/uploads/2023/12/$image , but this blocks other images as well.
Suggested filters:
none, cannot create one without breaking other images.

**Comment by RealEnder** [comment]
Yes, the filters were too broad. In this case we have to bite the bullet and selectively block every ad resource.
Tentative fix in a8b54bd978f107b56240695430d3f4c8cdf8bb8b
