### ISSUE TITLE
framar.bg : ad leftovers

### ISSUE THREAD

**Issue by Dani-1-2** [RealEnder/adblockbg#7]
Ad leftovers seen on https://www.forum.framar.bg/ and https://www.medpedia.framar.bg/
Suggested filters:
forum.framar.bg##div.bnr.forum_r_box:nth-of-type(1)
forum.framar.bg##div.bnr.forum_r_box:nth-of-type(2)
framar.bg##.c.box.column.banner-box.js-banner-box

**Comment by RealEnder** [comment]
Thanks, fixed in 8d09218ff4c3df9fda9aaba25683744c16dfcc76
